apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-todo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: go-todo/overlays/production
    repoURL: git@github.com:ekmsystems/argocd-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
