apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-renderer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: template-renderer/overlays/production
    repoURL: git@github.com:simax/argo-cd-apps-local.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
