---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: go-todo
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    go-todo:
      owner: jackcaldwell
      repository: go-todo
      webhook:
        endpoint: /go-todo
        port: "12000"
        method: POST
        url: https://webhook.ekmsvc.com
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: orders-api
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    orders-api:
      owner: ekmsystems
      repository: Ekm.Orders
      webhook:
        endpoint: /orders-api
        port: "12000"
        method: POST
        url: https://webhook.ekmsvc.com
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json
