apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - event-sources.yaml
  - sensors.yaml
  - githubcred.yaml
  - ingress.yaml
  - template-renderer-event-source.yaml
  - template-renderer-sensor.yaml
namespace: argo-events
