apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: template-renderer-webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: template-renderer
      eventSourceName: template-renderer
      eventName: template-renderer
      filters:
        data:
          - path: body.X-GitHub-Event
            type: string
            value:
              - push
          - path: body.ref
            type: string
            value:
              - refs/heads/kubernetes
  triggers:
    - template:
        name: trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: template-renderer-
                namespace: workflows
              spec:
                entrypoint: build
                serviceAccountName: workflow
                volumes:
                  - name: docker-config
                    configMap:
                      name: docker-config
                  - name: github-access
                    secret:
                      secretName: github-access
                      items:
                        - key: token
                          path: token
                        - key: user
                          path: user
                        - key: email
                          path: email
                templates:
                  - name: build
                    dag:
                      tasks:
                        - name: build
                          templateRef:
                            name: container-image
                            template: build-kaniko-git
                            clusterScope: true
                          arguments:
                            parameters:
                              - name: repo_url
                                value: ""
                              - name: repo_ref
                                value: ""
                              - name: repo_commit_id
                                value: ""
                              - name: container_image
                                value: 328373003584.dkr.ecr.eu-west-2.amazonaws.com/template-renderer
                              - name: container_tag
                                value: ""
                        - name: promote-staging
                          templateRef:
                            name: promote
                            template: promote
                            clusterScope: true
                          arguments:
                            parameters:
                              - name: environment
                                value: staging
                              - name: image_owner
                                value: 328373003584.dkr.ecr.eu-west-2.amazonaws.com
                              - name: image_name
                                value: go-todo
                              - name: tag
                                value: ""
                              - name: application_path
                                value: template-renderer
                          dependencies:
                            - build
                        - name: request-promote-production
                          templateRef:
                            name: request-promote
                            template: request-promote
                            clusterScope: true
                          arguments:
                            parameters:
                              - name: environment
                                value: production
                              - name: image_owner
                                value: 328373003584.dkr.ecr.eu-west-2.amazonaws.com
                              - name: image_name
                                value: template-renderer
                              - name: tag
                                value: ""
                              - name: application_path
                                value: template-renderer
                          dependencies:
                            - promote-staging
          parameters:
            - src:
                dependencyName: todo
                dataKey: body.repository.git_url
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
            - src:
                dependencyName: todo
                dataKey: body.ref
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
            - src:
                dependencyName: todo
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.2.value
            - src:
                dependencyName: todo
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
            - src:
                dependencyName: todo
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.1.arguments.parameters.3.value
            - src:
                dependencyName: todo
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.2.arguments.parameters.3.value
